-- 년, 월, 성별 별 상품 구매 회원 수 구하기
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER, COUNT(*) AS USERS
FROM 
    (SELECT *
    FROM ONLINE_SALE
    GROUP BY USER_ID, YEAR(SALES_DATE), MONTH(SALES_DATE)) AS S
    JOIN USER_INFO AS U
    ON S.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER