-- 식품분류별 가장 비싼 식품의 정보 조회하기
SELECT DISTINCT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM
    FOOD_PRODUCT AS F
    JOIN
    (SELECT CATEGORY, MAX(PRICE) AS PRICE, PRODUCT_NAME
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY) AS MF
    ON MF.PRICE = F.PRICE
WHERE F.CATEGORY = "과자" OR F.CATEGORY = "국" OR F.CATEGORY = "김치" OR F.CATEGORY = "식용유"
ORDER BY PRICE DESC