-- 즐겨찾기가 가장 많은 식당 정보 출력하기
SELECT T.FOOD_TYPE, T.REST_ID, T.REST_NAME, MAX_FAV.FAVORITES
FROM 
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) AS MAX_FAV
    JOIN REST_INFO AS T
    ON MAX_FAV.FOOD_TYPE = T.FOOD_TYPE
WHERE MAX_FAV.FAVORITES = T.FAVORITES
ORDER BY FOOD_TYPE DESC