-- 입양 시각 구하기(2)
SELECT T1.HOUR, IFNULL(T2.COUNT, "0") AS COUNT
FROM 
    (WITH RECURSIVE TEMP AS (
        SELECT 0 AS HOUR
        UNION ALL
        SELECT HOUR + 1 FROM TEMP
        WHERE HOUR < 23
    )
    SELECT HOUR, 0 AS COUNT
    FROM TEMP) AS T1
    LEFT JOIN
    (SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)) AS T2
    ON T1.HOUR = T2.HOUR