-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
SELECT T1.MONTH, T1.CAR_ID, T1.RECORDS
FROM
    (SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(MONTH(START_DATE) AND CAR_ID) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
    GROUP BY MONTH, CAR_ID) T1
    JOIN 
    (SELECT CAR_ID, COUNT(CAR_ID) AS TOTAL
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
    GROUP BY CAR_ID
    HAVING TOTAL >= 5
    ORDER BY CAR_ID) T2
    ON T1.CAR_ID = T2.CAR_ID
WHERE T1.RECORDS != 0
ORDER BY T1.MONTH, T1.CAR_ID DESC