-- 저자 별 카테고리 별 매출액 집계하기
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, CB.CATEGORY, SUM(CB.TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR AS A
    RIGHT JOIN 
        (SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, B.PRICE, S.SALES, B.PRICE*S.SALES AS TOTAL_SALES, S.SALES_DATE
         FROM BOOK AS B
            RIGHT JOIN BOOK_SALES AS S
            ON B.BOOK_ID = S.BOOK_ID) AS CB
    ON A.AUTHOR_ID = CB.AUTHOR_ID
WHERE YEAR(SALES_DATE) = "2022" AND MONTH(SALES_DATE) = "01"
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC