-- 카테고리 별 도서 판매량 집계하기
SELECT B.CATEGORY, SUM(BS.BOOKS_SALES) AS TOTAL_SALES
FROM BOOK AS B
    JOIN 
    (SELECT BOOK_ID, SUM(SALES) AS BOOKS_SALES
    FROM BOOK_SALES 
    WHERE YEAR(SALES_DATE) = "2022" AND MONTH(SALES_DATE) = "01"
    GROUP BY BOOK_ID) AS BS
    ON B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY