SELECT *
FROM 
    (SELECT CAR_ID, IF(END_DATE < "2022-10-16 00:00:00" OR START_DATE > "2022-10-16 23:59:59", "대여 가능", "대여중") AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID, AVAILABILITY
    ORDER BY CAR_ID DESC, AVAILABILITY DESC) AS CT
GROUP BY CAR_ID