-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
WITH NEW_H AS
    (SELECT *
    FROM
        (SELECT CAR_ID, IF(START_DATE > DATE("2022-11-30") OR END_DATE < DATE("2022-11-01"), TRUE, FALSE) AS AVAILABILITY
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID, AVAILABILITY
        ORDER BY CAR_ID, AVAILABILITY) AS CH
    GROUP BY CAR_ID)
SELECT * 
FROM
    (SELECT ABLE.CAR_ID, ABLE.CAR_TYPE, 
        FLOOR(30 * DAILY_FEE * (100 - CAST(SUBSTR(DISCOUNT_RATE, -1) AS UNSIGNED)) / 100) AS FEE
    FROM
        (SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR AS C
            JOIN NEW_H
            ON C.CAR_ID = NEW_H.CAR_ID
        WHERE CAR_TYPE IN ("세단", "SUV") AND NEW_H.AVAILABILITY = TRUE) AS ABLE
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
        ON ABLE.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE LIKE "30%") AS RESULT
WHERE FEE >= 500000 AND FEE <= 2000000