-- 상품을 구매한 회원 비율 구하기
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, COUNT(*) AS PUCHASED_USERS, ROUND(COUNT(*) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = "2021"), 1) AS PURCHASED_RATIO
FROM 
    (SELECT SALES_DATE, USER_ID
     FROM ONLINE_SALE
     GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_ID) AS S
     JOIN USER_INFO AS U
     ON U.USER_ID = S.USER_ID
WHERE YEAR(U.JOINED) = "2021"
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR, MONTH