-- 5월 식품들의 총매출 조회하기
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT)*P.PRICE AS TOTAL_SALES
FROM FOOD_ORDER AS O
    JOIN FOOD_PRODUCT AS P
    ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = "2022" AND MONTH(PRODUCE_DATE) = "05"
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID