-- 상품 별 오프라인 매출 구하기
SELECT P.PRODUCT_CODE, SUM(P.PRICE*SALES_AMOUNT) AS SALES
FROM PRODUCT AS P
    RIGHT JOIN OFFLINE_SALE AS S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC