-- 그룹별 조건에 맞는 식당 목록 출력하기
WITH RM AS
    (SELECT M.MEMBER_ID, M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE, COUNT(*) AS REVIEW_NUM
    FROM REST_REVIEW AS R
        JOIN MEMBER_PROFILE AS M
        ON R.MEMBER_ID = M.MEMBER_ID
    GROUP BY MEMBER_ID)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW AS R
    JOIN MEMBER_PROFILE AS M
    ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN
    (SELECT RM.MEMBER_ID
    FROM RM, (SELECT MAX(REVIEW_NUM) AS MAX_REVIEW_NUM FROM RM) AS MAX_RM
    WHERE RM.REVIEW_NUM = MAX_RM.MAX_REVIEW_NUM) 
ORDER BY REVIEW_DATE, REVIEW_TEXT