-- 자동차 대여 기록 별 대여 금액 구하기
\SELECT HISTORY_ID, CAST((DAILY_FEE * ((100 - IF(D.DISCOUNT_RATE IS NULL, 0, D.DISCOUNT_RATE)) / 100)) * DURATION AS UNSIGNED) AS FEE
FROM
    (SELECT H.HISTORY_ID, C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, DATEDIFF(END_DATE,START_DATE)+1 AS DURATION
    FROM CAR_RENTAL_COMPANY_CAR AS C
        RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        ON C.CAR_ID = H.CAR_ID) AS CH
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
    ON CH.CAR_TYPE = D.CAR_TYPE 
    AND DURATION_TYPE LIKE CASE 
        WHEN CH.DURATION < 7 THEN "0%"
        WHEN CH.DURATION < 30 THEN "7%"
        WHEN CH.DURATION < 90 THEN "30%"
        ELSE "90%"
    END
WHERE CH.CAR_TYPE = "트럭"
ORDER BY FEE DESC, HISTORY_ID DESC