-- 대여 기록이 존재하는 자동차 리스트 구하기
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
    LEFT JOIN
    (SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE LIKE "2022-10%"
    GROUP BY CAR_ID) AS H
    ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = "세단" AND H.HISTORY_ID IS NOT NULL
ORDER BY C.CAR_ID DESC