SELECT AP.APNT_NO, AP.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM
    (SELECT A.APNT_NO, A.APNT_YMD, P.PT_NO, PT_NAME, MCDP_CD, APNT_CNCL_YN, MDDR_ID
    FROM APPOINTMENT AS A
        JOIN PATIENT AS P
        ON P.PT_NO = A.PT_NO) AS AP
    JOIN DOCTOR AS D
    ON AP.MDDR_ID = D.DR_ID
WHERE DATE_FORMAT(AP.APNT_YMD, "%Y-%m-%d") = "2022-04-13" AND AP.MCDP_CD = "CS" AND AP.APNT_CNCL_YN = "N"
ORDER BY AP.APNT_YMD
